package by.evgen.productservice.model;

public enum Category {
    REAL_ESTATE,
    AUTO_AND_TRANSPORT,
    REPAIR_AND_CONSTRUCTION,
    HOBBIES_SPORTS_AND_TOURISM,
    FURNITURE,
    WOMEN_WARDROBE,
    ANIMALS,
    PHONES_AND_TABLETS,
    ELECTRONICS,
    COMPUTER_TECHNOLOGY,
    APPLIANCES,
    MEN_WARDROBE,
    OTHERS
}