server:
  port: ${EUREKA_PORT}

spring:
  config:
    import: D:\diploma\System-Online-Auction\diploma\.env
  application:
    name: eureka-server

logging:
  level:
    com:
      netflix:
        discovery: off
        eureka: off

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
    register-with-eureka: false
    fetch-registry: false
