server:
  port: 8761

spring:
  application:
    name: eureka-server

logging:
  level:
    com:
      netflix:
        discovery: off
        eureka: off

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
