server:
  port: ${PRODUCT_SERVICE_PORT}

spring:
  config:
    import: D:\diploma\System-Online-Auction\diploma\.env
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${PRODUCT_SERVICE_POSTGRES_HOST}:${PRODUCT_SERVICE_POSTGRES_PORT}/${PRODUCT_SERVICE_POSTGRES_DATABASE_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/