server:
  port: ${API_GATEWAY_PORT}

spring:
  config:
    import: D:\diploma\System-Online-Auction\diploma\.env
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authentication-service
          uri: lb://eureka-client
          predicates:
            - Path= /auth/**

        - id: user-service
          uri: lb://eureka-client
          predicates:
            - Path= /users/**

        - id: auction-service
          uri: lb://eureka-client
          predicates:
            - Path= /auctions/**
            - Path= /basket/**
            - Path= /bids/**

        - id: card-service
          uri: lb://eureka-client
          predicates:
            - Path= /cards/**

        - id: product-service
          uri: lb://eureka-client
          predicates:
            - Path= /products/**

      default-filters:
        - AddResponseHeader=X-Response-Default-Red, Default-Blue
        - PrefixPath=/api/v1
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/