server:
  port: 8085

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  application:
    name: auction-service
  datasource:
    url: jdbc:postgresql://localhost:5437/auction_db
    username: postgres
    password: 27112001jeka
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/